### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by davidr1234** [skinkie/reference#132]
@skinkie @ue71603

Before re-visiting the documentation (https://github.com/skinkie/reference/issues/129) I'd like to give our folder structure a re-juvination. Hoping this is not a duplicate

Here's a suggestion for it - if agreed upon I'd open a feature-branch for it

IMPORTANT: <b>I only write about gtfs-netex-test</b>. 
-> I would almost argue opening a repo only for the data in this folder. At the moment the whole repo appears a bit "cluttered".

folder structure:

transform_scripts # contains all main scripts to transform among the standards
	- to_db
	- from_db
	- between_standards

models # code for modelling data structures
	- netex
	- siri

utils # code used to support the transformation and analysis of the data
	- netexio -> rename database_io
	- rrtimetable -> what is this exactly? @skinkie @ue71603 
	- transformations -> @skinkie/@ue71603 not quite sure here
	- vdvserver -> maybe make this more generic? https://github.com/skinkie/reference/issues/128

tests # contains tests, such as the pipelines @ue71603 created in aux_tests.txt
	- example_inputs
	- example_outputs

conf # any configuration files, e.g., siri.conf, requirements.txt, etc.

ALSO: I will create a "code_looking_for_a_home" folder for all code I could not clearly assing to any of the above folders

-----
MORE: I suggest removing the following folders from the official branch, as they seem to be folders and files that you respectively use for local purposes
	- netex-output -> empty
	- netex-output-epip -> empty
	- gtfs -> empty
	- netexrrrr -> not sure, what is this exactly? @skinkie @ue71603 
	- tmp -> for obvious reasons, export-tables.py not used?

**Comment by skinkie** [comment]
I have already tested folders, this won't work for 'main scripts' because of the imports should be relative.
The transform folder contains the current projection code (a true transitive concept-to-concept translation).
The import functionality to get for example GTFS, HAFAS, IFF or Optibus into NeTEx-concetps could be in a separate folder.
I don't think the 'utils' subfolder idea with folders under it is something I would support.

As discussed with @ue71603 before, no data examples in the repo itself.

requirements.txt must be also in the 'root' folder of the project.

netexrrrr is an export script for NeTEx to rrrr (so something like the db-to-gtfs).

**Comment by ue71603** [comment]
Stefan will clean up his files and I do mine.  We keep the scripts where they are. input/output won't be in here.  scripts and assertionswill be stored in the folder scripts then the aux_-folders will beremoved.

If ok, I close this one here.
