### ISSUE TITLE
import.py & no feed_info.txt

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#17]
Either we fill in a line or the import should block.
Because it will break during the transform, if this is not there.
I did this with a dummy entry.
What do you prefer?

**Comment by skinkie** [comment]
If feed_info is empty it should generate it from the NeTEx side. Hence check the output of the feed_info query, if not exists, at least create a dummy datasource / codespace, if a single agency exists, use that otherwise the first one.
The validity computation can be delayed until the calendars have processed.

**Comment by ue71603** [comment]
Done in PR #18
