### ISSUE TITLE
What was your idea to pass the logger into transformers?

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#172]
Can you provide a concrete example where/how a logger should be used with transformers?

**Comment by ue71603** [comment]
I don't think I did that

**Comment by ue71603** [comment]
You really want me to understand your generators :-)

**Comment by ue71603** [comment]
my ideas: Orient about this: https://stackoverflow.com/questions/15727420/using-logging-in-multiple-modules  
This probably means rewritting the logging and within the transformers log_once and the other ones would not be available. Instead of having multiple log files now, I guess we would have only one.  Should I write some code?

**Comment by skinkie** [comment]
I'll take a peak. Now working to get EPIP working again.

**Comment by ue71603** [comment]
makes me happy.
