### ISSUE TITLE
Decide what to do with broken input

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#193]
If we state we cannot handle explicitly broken input, that is fine with me. But at some places the code takes for example a dictionary lookup, and will (and does) fail when some referenced values are in fact not present. Do we consider it a bug if an actual python error is thrown when processing? At what milestone should this be resolved?

**Comment by ue71603** [comment]
example?

**Comment by skinkie** [comment]
Take for example TESO. If the Dutch central stop file is not loaded, then the QuayRefs of the PassengerStopAssignment won't work.

**Comment by ue71603** [comment]
He Stefan: 
- I can't test anything, as epip_db_to_xml.py always dies (not caring, which data I use. Perhaps this is related to this one.
- I see. In the real world breaking on input failures of this magnitude would be ok. swiss4 is already a crude manual reduction. And from what you write with JourneyMeetings and InterchangeRules. That's where stuff that was only in other - not included timetable files happens.  
- I usually use dict.get() as there the problem is easier to handle, when nothing is returned.
- If it is only ServiceJourneys missing (in InterchangeRule stuff like that, I think we could proceed by just dropping those . JourneyMeeting, InterchangeRule, CoupledJourneyPart for the rest. dying is probably the best. If this is too cumbersome, then we reject it always, I have to drop swiss4. As soon as related_explorer works, I can then build examples from the main file (once we have a swiss as epip).

**Comment by ue71603** [comment]
@skinkie  Do we need something like: with validation or without (then it assumes that the references will be corrected later?)

**Comment by skinkie** [comment]
I think we can do our validation _interally_ with our reference table. And then check if all objects exist. And maybe even report after import that they don't?

**Comment by ue71603** [comment]
ok
